### PR TITLE
Fix(be 745) Add pagination for students lists

### LINKED ISSUE #745: Reports - Bug - Student lists: Pagination is broken in different student lists.
The pagination of students for different regions is failing delivering all the result in a single list and is not possible to set different sizes of pages.

Student monitoring

Image

Dynamic heatmap chart

Image

Dynamic Column chart

Image

Summary Column Chart

Image

The Summary Heatmap chart currently is affected by another bug but is highly probable to have the same issue.

### PR DESCRIPTION
**Pull request by judithmarg-dev**
### Problem
The pagination to watch and manipulate the list of students in monitoring students, dynamic heatmap chart, dynamic column chart and summary column chart did not work correctly, always it displayed all values in the list.

### Root Cause
GetStudentsByFilters,  GetCohortTopRiskStudents and GetCohortTopRiskStudentsByComponent did not return PagedResult, instead they used Lists. Lack of pagination in those endpoints.

## Type of change

- [X] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Documentation Improvements
- [ ] Others:

## Checklist

- [ ] Have the requirements been met?
- [ ] Is the code easy to read?
- [ ] Do unit tests pass?
- [ ] Is the code formatted correctly?

## C# Checklist

- [ ] Does this code make correct use of asynchronous programming constructs, including proper use of await and Task.WhenAll including CancellationTokens?
- [ ] Does the code handle exceptions correctly
- [ ] Is the code subject to concurrency issues? Are shared objects properly protected?
- [ ] There are no complex long boolean expressions (i.e; x = isMatched ? shouldMatch ? doesMatch ? blahBlahBlah).
- [ ] There are no negatively named booleans (i.e; notMatchshould be isMatch and the logical negation operator (!) should be used.
- [ ] Are internal vs private vs public classes and methods used the right way?

### CODE REVIEW

File: src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/ErasEvaluationDetailsViewRepository.cs [hunk 1]
```diff
@@ -6,12 +6,16 @@
 
 using Eras.Application.Contracts.Persistence;
 using Eras.Application.Models.Response.Controllers.EvaluationDetailsController;
+using Eras.Application.Utils;
 using Eras.Domain.Entities;
 using Eras.Infrastructure.Persistence.PostgreSQL.Entities;
 using Eras.Infrastructure.Persistence.PostgreSQL.Mappers;
 
+using Microsoft.AspNetCore.Mvc.RazorPages;
```
Comment (mmoralesv) [inline src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/ErasEvaluationDetailsViewRepository.cs]: Is this references used for something?

**Review by mmoralesv — DISMISSED** [review]

File: src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/ErasEvaluationDetailsViewRepository.cs (hunk 1 above)
Comment (judithmarg-dev) [reply src/Eras.Infrastructure/Persistence/PostgreSQL/Repositories/ErasEvaluationDetailsViewRepository.cs]: No, it is not. It is an unused import. I removed it in `c41f7f0` commit

**Review by mmoralesv — APPROVED** [review]
