### PR TITLE
fix: correct KPI percentage change calculation using domain-specific …

### LINKED ISSUE #395: [Bug] Home > Overview: KPI percentage values does not change
**Description**
KPI percentages located in the Home page under Overview section do not change its value they are always shown as 100% even evaluations has been removed and decreased the current number

**Pre-conditions**
- Service provider configured successfully
- Existing evaluation in the system

**Steps To Reproduce**
1. Log in into the system
2. Navigate to Home from left side bar menu. Make sure v2 version is loaded
https://10.24.80.173/home?homev2=true
3. Check the current Overview components: Number of Students, Polls Answered, Evaluations and take note of the percentages. All of them are shown as 100%
Image
4. Navigate to Evaluations and then add evaluations with different status
 Finished, not started yet
Image
5. Go back to Home page and verify number of evaluation has change but percentage not, - Failed
Looks like the percentages do not change from 100%
Image
6. Repeat 5-5 to check the other components  Number of Students, Polls Answered, and noticed that percentages do not change

**Actual Result:**
KPI percentages in the Home page under Overview section are shown as 100% and not seems to change from that value

**Expected Result"**
KPI percentages in the Home page under Overview section should change depending of the logic behind defined for them, please clarify the expectation for these values.

**Environment details**
 - Environment: Development
 - Browser Chrome

### PR DESCRIPTION
**Pull request by LuFeBeVi**
## Description

This fix corrects how KPI percentage changes are calculated by using the appropriate date for each entity instead of a generic created_at field.

Each repository now filters by its relevant date (e.g., StartDate for evaluations, FinishedAt for poll instances), and cohort date ranges are handled in UTC to avoid timezone issues.

As a result, KPI percentages now accurately reflect the change between the current and previous periods instead of always returning 100%.

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Documentation Improvements
- [ ] Others:

## Checklist

- [ ] Have the requirements been met?
- [ ] Is the code easy to read?
- [ ] Do unit tests pass?
- [ ] Is the code formatted correctly?

## C# Checklist

- [ ] Does this code make correct use of asynchronous programming constructs, including proper use of await and Task.WhenAll including CancellationTokens?
- [ ] Does the code handle exceptions correctly
- [ ] Is the code subject to concurrency issues? Are shared objects properly protected?
- [ ] There are no complex long boolean expressions (i.e; x = isMatched ? shouldMatch ? doesMatch ? blahBlahBlah).
- [ ] There are no negatively named booleans (i.e; notMatchshould be isMatch and the logical negation operator (!) should be used.
- [ ] Are internal vs private vs public classes and methods used the right way?

### CODE REVIEW

File: src/Eras.Application/Utils/CohortsHelper.cs [hunk 1]
```diff
@@ -77,15 +77,19 @@ public static (DateTime Start, DateTime End) GetCurrentCohortRange()
...
+            new DateTime(now.Year, 12, 31, 23, 59, 59, DateTimeKind.Utc));
     }
 
     public static (DateTime Start, DateTime End) GetPreviousCohortRange()
     {
         var now = DateTime.UtcNow;
         return now.Month <= 6
-            ? (new DateTime(now.Year - 1, 7, 1), new DateTime(now.Year - 1, 12, 31, 23, 59, 59, DateTimeKind.Utc))
-            : (new DateTime(now.Year, 1, 1), new DateTime(now.Year, 6, 30, 23, 59, 59, DateTimeKind.Utc));
+            ? (new DateTime(now.Year - 1, 7, 1, 0, 0, 0, DateTimeKind.Utc),
```
Comment (judithmarg-dev) [inline src/Eras.Application/Utils/CohortsHelper.cs]: I think it could be restrictive, so instead of basing it on 2025 (now Year -1), it could be based on 2016, as seen in the process evaluation creation

Comment (LuFeBeVi) [reply src/Eras.Application/Utils/CohortsHelper.cs]: Thanks for the observation! Just to clarify, we are actually not restricting the historical data.
The main metric (Value) already includes all historical records (from 2016 to date) because it uses CountAsync() without any date filters.
The date ranges (CurrentCohort and PreviousCohort) are strictly used to calculate the trend (percentageChange). Since this is the main dashboard for Jala university, this comparison is designed to show the activity of the current ongoing semester versus the immediately previous one. This allows administrators to track real time engagement for the current academic cycle.

Additionally, I refactored the now.Year - 1 logic to use .AddMonths(-6). This makes the cohort period calculation completely dynamic and reliable regardless of the current year.

**Review by judithmarg-dev — APPROVED** [review]
